// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/base/Button.vue')['default']
    ButtonGroup: typeof import('./components/base/ButtonGroup.vue')['default']
    Checkbox: typeof import('./components/base/Checkbox.vue')['default']
    Code: typeof import('./components/Code.vue')['default']
    CopyButton: typeof import('./components/base/CopyButton.vue')['default']
    Empty: typeof import('./components/Empty.vue')['default']
    Headers: typeof import('./components/Headers.vue')['default']
    Icon: typeof import('./components/base/Icon.vue')['default']
    Input: typeof import('./components/base/Input.vue')['default']
    List: typeof import('./components/List.vue')['default']
    MainPanel: typeof import('./components/MainPanel.vue')['default']
    Params: typeof import('./components/Params.vue')['default']
    Query: typeof import('./components/Query.vue')['default']
    Response: typeof import('./components/Response.vue')['default']
    Scroll: typeof import('./components/base/Scroll.vue')['default']
    Select: typeof import('./components/base/Select.vue')['default']
    SplitPane: typeof import('./components/base/SplitPane.vue')['default']
    Switch: typeof import('./components/base/Switch.vue')['default']
    Table: typeof import('./components/base/Table.vue')['default']
    Toggle: typeof import('./components/base/Toggle.vue')['default']
    Tooltip: typeof import('./components/base/Tooltip.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
    Variables: typeof import('./components/Variables.vue')['default']
  }
}
